// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QL_CuaHangDienThoai.Data;

#nullable disable

namespace QL_CuaHangDienThoai.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250722224036_AddSoDTToQuanTriVien")]
    partial class AddSoDTToQuanTriVien
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("QL_CuaHangDienThoai.Models.ChiTietGioHang", b =>
                {
                    b.Property<string>("MaGH")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("MaGH");

                    b.Property<string>("MaDT")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("MaDT");

                    b.Property<DateTime>("NgayThem")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayThem");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int")
                        .HasColumnName("SoLuong");

                    b.HasKey("MaGH", "MaDT");

                    b.HasIndex("MaDT");

                    b.ToTable("CHITIETGIOHANG");
                });

            modelBuilder.Entity("QL_CuaHangDienThoai.Models.ChiTietHoaDon", b =>
                {
                    b.Property<string>("MaHD")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("MaHD");

                    b.Property<string>("MaDT")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("MaDT");

                    b.Property<decimal>("DonGia")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("DonGia");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int")
                        .HasColumnName("SoLuong");

                    b.HasKey("MaHD", "MaDT");

                    b.HasIndex("MaDT");

                    b.ToTable("CHITIETHOADON");
                });

            modelBuilder.Entity("QL_CuaHangDienThoai.Models.DienThoai", b =>
                {
                    b.Property<string>("MaDT")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("MaDT");

                    b.Property<decimal>("DonGia")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("DonGia");

                    b.Property<int>("SoLuongTon")
                        .HasColumnType("int")
                        .HasColumnName("SoLuongTon");

                    b.Property<string>("TenDT")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TenDT");

                    b.HasKey("MaDT");

                    b.ToTable("DIENTHOAI");
                });

            modelBuilder.Entity("QL_CuaHangDienThoai.Models.GioHang", b =>
                {
                    b.Property<string>("MaGH")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("MaGH");

                    b.Property<string>("MaKH")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("MaKH");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao");

                    b.HasKey("MaGH");

                    b.HasIndex("MaKH");

                    b.ToTable("GIOHANG");
                });

            modelBuilder.Entity("QL_CuaHangDienThoai.Models.HoaDon", b =>
                {
                    b.Property<string>("MaHD")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("MaHD");

                    b.Property<string>("MaKH")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("MaKH");

                    b.Property<string>("MaQTV")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("MaQTV");

                    b.Property<DateTime>("NgayLap")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayLap");

                    b.Property<decimal>("TongTien")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("TongTien");

                    b.HasKey("MaHD");

                    b.HasIndex("MaKH");

                    b.HasIndex("MaQTV");

                    b.ToTable("HOADON");
                });

            modelBuilder.Entity("QL_CuaHangDienThoai.Models.KhachHang", b =>
                {
                    b.Property<string>("MaKH")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("MaKH");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Email");

                    b.Property<string>("HoTen")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("HoTen");

                    b.Property<string>("SoDT")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("SoDT");

                    b.Property<string>("TenDangNhap")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TenDangNhap");

                    b.HasKey("MaKH");

                    b.HasIndex("TenDangNhap")
                        .IsUnique()
                        .HasFilter("[TenDangNhap] IS NOT NULL");

                    b.ToTable("KHACHHANG");
                });

            modelBuilder.Entity("QL_CuaHangDienThoai.Models.QuanTriVien", b =>
                {
                    b.Property<string>("MaQTV")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("MaQTV");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Email");

                    b.Property<string>("HoTen")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("HoTen");

                    b.Property<string>("SoDT")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("SoDT");

                    b.Property<string>("TenDangNhap")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TenDangNhap");

                    b.HasKey("MaQTV");

                    b.HasIndex("TenDangNhap")
                        .IsUnique()
                        .HasFilter("[TenDangNhap] IS NOT NULL");

                    b.ToTable("QUANTRIVIEN");
                });

            modelBuilder.Entity("QL_CuaHangDienThoai.Models.TaiKhoan", b =>
                {
                    b.Property<string>("TenDangNhap")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TenDangNhap");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Email");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("MatKhau");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("VaiTro");

                    b.HasKey("TenDangNhap");

                    b.ToTable("TAIKHOAN");

                    b.HasCheckConstraint("CK_TaiKhoan_VaiTro", "[VaiTro] IN ('khach', 'admin', 'nhanvien')");
                });

            modelBuilder.Entity("QL_CuaHangDienThoai.Models.ThanhToanTrucTuyen", b =>
                {
                    b.Property<string>("MaThanhToan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MaThanhToan");

                    b.Property<string>("MaGiaoDichNganHang")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("MaGiaoDichNganHang");

                    b.Property<string>("MaHD")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("MaHD");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayCapNhat");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao");

                    b.Property<string>("PhuongThucThanhToan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PhuongThucThanhToan");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("SoTien");

                    b.Property<string>("ThongTinThem")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ThongTinThem");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TrangThai");

                    b.HasKey("MaThanhToan");

                    b.HasIndex("MaHD");

                    b.ToTable("THANHTOANTRUCTUYEN");
                });

            modelBuilder.Entity("QL_CuaHangDienThoai.Models.ChiTietGioHang", b =>
                {
                    b.HasOne("QL_CuaHangDienThoai.Models.DienThoai", "DienThoai")
                        .WithMany()
                        .HasForeignKey("MaDT")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QL_CuaHangDienThoai.Models.GioHang", "GioHang")
                        .WithMany("ChiTietGioHangs")
                        .HasForeignKey("MaGH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DienThoai");

                    b.Navigation("GioHang");
                });

            modelBuilder.Entity("QL_CuaHangDienThoai.Models.ChiTietHoaDon", b =>
                {
                    b.HasOne("QL_CuaHangDienThoai.Models.DienThoai", "DienThoai")
                        .WithMany("ChiTietHoaDons")
                        .HasForeignKey("MaDT")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QL_CuaHangDienThoai.Models.HoaDon", "HoaDon")
                        .WithMany("ChiTietHoaDons")
                        .HasForeignKey("MaHD")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DienThoai");

                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("QL_CuaHangDienThoai.Models.GioHang", b =>
                {
                    b.HasOne("QL_CuaHangDienThoai.Models.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("MaKH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("QL_CuaHangDienThoai.Models.HoaDon", b =>
                {
                    b.HasOne("QL_CuaHangDienThoai.Models.KhachHang", "KhachHang")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaKH");

                    b.HasOne("QL_CuaHangDienThoai.Models.QuanTriVien", "QuanTriVien")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaQTV");

                    b.Navigation("KhachHang");

                    b.Navigation("QuanTriVien");
                });

            modelBuilder.Entity("QL_CuaHangDienThoai.Models.KhachHang", b =>
                {
                    b.HasOne("QL_CuaHangDienThoai.Models.TaiKhoan", "TaiKhoan")
                        .WithOne("KhachHang")
                        .HasForeignKey("QL_CuaHangDienThoai.Models.KhachHang", "TenDangNhap");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("QL_CuaHangDienThoai.Models.QuanTriVien", b =>
                {
                    b.HasOne("QL_CuaHangDienThoai.Models.TaiKhoan", "TaiKhoan")
                        .WithOne("QuanTriVien")
                        .HasForeignKey("QL_CuaHangDienThoai.Models.QuanTriVien", "TenDangNhap");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("QL_CuaHangDienThoai.Models.ThanhToanTrucTuyen", b =>
                {
                    b.HasOne("QL_CuaHangDienThoai.Models.HoaDon", "HoaDon")
                        .WithMany()
                        .HasForeignKey("MaHD")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("QL_CuaHangDienThoai.Models.DienThoai", b =>
                {
                    b.Navigation("ChiTietHoaDons");
                });

            modelBuilder.Entity("QL_CuaHangDienThoai.Models.GioHang", b =>
                {
                    b.Navigation("ChiTietGioHangs");
                });

            modelBuilder.Entity("QL_CuaHangDienThoai.Models.HoaDon", b =>
                {
                    b.Navigation("ChiTietHoaDons");
                });

            modelBuilder.Entity("QL_CuaHangDienThoai.Models.KhachHang", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("QL_CuaHangDienThoai.Models.QuanTriVien", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("QL_CuaHangDienThoai.Models.TaiKhoan", b =>
                {
                    b.Navigation("KhachHang");

                    b.Navigation("QuanTriVien");
                });
#pragma warning restore 612, 618
        }
    }
}
